# Generated by Django 3.1 on 2020-08-19 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Group',
            fields=[
                ('identifier', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'food_group_specified_name',
                'ordering': ['identifier', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('default_days_to_exp', models.PositiveSmallIntegerField()),
                ('food_group_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='food.food_group')),
            ],
        ),
    ]
