# Generated by Django 3.1 on 2020-08-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table='food',
        ),
        migrations.AlterModelTable(
            name='food_group',
            table='food_group',
        ),
    ]
