# Generated by Django 3.1.6 on 2021-03-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_group',
            name='image',
            field=models.ImageField(null=True, upload_to='food_groups'),
        ),
    ]
