# Generated by Django 3.1 on 2020-09-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
        migrations.AlterField(
            model_name='food_group',
            name='food_group',
            field=models.CharField(max_length=128),
        ),
    ]
