# Generated by Django 3.1 on 2020-09-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200903_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='default_days_to_exp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
