# Generated by Django 3.1 on 2020-08-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200819_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fridge_item',
            field=models.BooleanField(default=False),
        ),
    ]
