# Generated by Django 3.1 on 2020-08-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_fridge_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='fridge_item',
        ),
    ]
