# Generated by Django 3.1 on 2020-08-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_food_fridge_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_group',
            options={},
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_group_id',
            new_name='food_group',
        ),
        migrations.RenameField(
            model_name='food_group',
            old_name='category',
            new_name='food_group',
        ),
        migrations.RenameField(
            model_name='food_group',
            old_name='identifier',
            new_name='food_group_id',
        ),
        migrations.AddField(
            model_name='food_group',
            name='image',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
