# Generated by Django 3.1 on 2020-08-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200819_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_group',
            new_name='food_group_id',
        ),
    ]
