# Generated by Django 3.1 on 2020-08-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200821_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_group_id',
            new_name='food_group',
        ),
    ]
