# Generated by Django 3.1 on 2020-09-03 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuisine', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cuisine',
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'diet',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('measurement_unit', models.CharField(max_length=128)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('meal_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_type', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'meal_type',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(default='')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.cuisine')),
                ('diets', models.ManyToManyField(to='recipes.Diet')),
                ('foods', models.ManyToManyField(related_name='recipes', through='recipes.Ingredient', to='food.Food')),
                ('meal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.meal_type')),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
