# Generated by Django 3.1 on 2020-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200821_1531'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='foods',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Ingredient', to='food.Food'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
