# Generated by Django 3.1 on 2020-08-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200821_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.cuisine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.diet'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='recipes.meal_type'),
        ),
    ]
