# Generated by Django 3.1 on 2020-09-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200903_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unlisted_food',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
