# Generated by Django 3.1 on 2020-08-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200821_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='diets_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(null=True, to='recipes.Diet'),
        ),
    ]
