# Generated by Django 3.1.6 on 2021-08-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210805_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
