# Generated by Django 3.1 on 2020-09-03 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
            ],
            options={
                'db_table': 'fridge_item',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('origin_account_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('wasted_count', models.PositiveIntegerField(default=0)),
                ('eaten_count', models.PositiveIntegerField(default=0)),
                ('produce_wasted', models.PositiveIntegerField(default=0)),
                ('meat_wasted', models.PositiveIntegerField(default=0)),
                ('dairy_wasted', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('fridge', models.ManyToManyField(related_name='users', through='users.Fridge_Item', to='food.Food')),
                ('saved_recipes', models.ManyToManyField(to='recipes.Recipe')),
                ('shopping_list', models.ManyToManyField(to='food.Food')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='fridge_item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
