# Generated by Django 3.1 on 2020-09-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200903_1608'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge_item',
            name='unlisted_food',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Shopping_List_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlisted_food', models.CharField(max_length=128, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'shopping_list',
            },
        ),
    ]
