# Generated by Django 3.1 on 2020-09-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.Recipe'),
        ),
    ]
