# Generated by Django 3.1 on 2020-09-07 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200907_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='origin_account_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
