# Generated by Django 3.1 on 2020-09-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200903_1608'),
        ('users', '0002_auto_20200903_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shopping_list',
        ),
        migrations.AddField(
            model_name='user',
            name='shopping',
            field=models.ManyToManyField(through='users.Shopping_List_Item', to='food.Food'),
        ),
    ]
