# Generated by Django 3.1 on 2020-09-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200903_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shopping',
            new_name='shopping_list',
        ),
    ]
