# Generated by Django 3.1.6 on 2021-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200921_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_list_item',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
