# Generated by Django 3.1.6 on 2021-06-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_owned_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owned_recipes',
        ),
    ]
