# Generated by Django 3.1.6 on 2021-08-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_owned_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopping_list_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
